displayName=Golem Crafting
author=Proddy
description=A plugin to help with Wyrmscraig Golem Crafting.
tags=wyrmscraig,sunstone,golem,crafting
version=2.7
plugins=org.zhbot.golem_crafting.GolemCraftingPlugin
build=standard